### ISSUE TITLE
Invite Response

### ISSUE THREAD

**Issue by Skillkiller** [zekroTJA/KnechtBot2#1]
Der Invite Befehl von dem Bot gibt glaube ich keine Rückmeldung an den User, so kann es passieren das der User den Invite Befehl mehrmals ausführt weil er denkt es hat nicht geklappt.

Wenn dies nicht stimmt bitte den Issue schließen 👍

**Comment by zekroTJA** [comment]
Hm sollte eigentlich funktionieren, müsste man aber mal genauer testen ^^
https://github.com/zekroTJA/KnechtBot2/blob/master/funcs.coffee#L99

**Edit:**
Hab nochmal in den Test-Messages nachgeschaut und die Message gefunden.
Können ja trotzdem den nächsten Bot Invite darauf mal prüfen und den Bot Owner fragen ob er eine message bekommen hat.
![sc](http://zekro.de/ss/Discord_2017-10-28_01-28-18.jpg)

Danke trotzdem :)
