### ISSUE TITLE
Rolle wird beim Kicken eines Bot's entfernt

### ISSUE THREAD

**Issue by Skillkiller** [zekroTJA/KnechtBot2#3]
Hey,
ich habe auf dem Server mehrer Bots gehabt, nachdem ich einer meiner 4 Bots kickt habe wurde mir schon die Rolle "Bot Owner" entfernt obwohl ich ja noch 3 aktive hatte.

Liebe Grüße
Skillkiller

**Comment by zekroTJA** [comment]
Okay, hab tatsächlich beim erstellen nicht erwartet, dass User mehrere Userbots haben werden :D 
Egal, werds versuchen, anzugehen ^^
